### ISSUE TITLE
哥哥好

### ISSUE THREAD

**Issue by xiaopohou** [SkyChenSky/Sikiro.SMS#1]
谢谢你的分享，你这个sms的项目可具备生产环境使用吗、我想用！

**Comment by SkyChenSky** [comment]
可以的，这项目在之前公司在用的。这项目其实没什么特别技术难度，主要通过博文里的设计思想来实现了。组件的使用是其次，核心还是需要了解思想。

**Comment by xiaopohou** [comment]
好的！谢谢 ！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈珙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 中午1:33
收件人:&nbsp;"SkyChenSky/Sikiro.SMS"<Sikiro.SMS@noreply.github.com&gt;;
抄送:&nbsp;"└Monkey丶"<393331943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SkyChenSky/Sikiro.SMS] 哥哥好 (#1)





 
可以的，这项目在之前公司在用的。这项目其实没什么特别技术难度，主要通过博文里的设计思想来实现了。组件的使用是其次，核心还是需要了解思想。
